export async function onRequest(context) {
  const response = await context.next();
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("text/html")) return response;

  let html = await response.text();

  html = html.replace(
    `<div class="posSubBtns"><button class="postip" id="tipChangeButton" type="button">Tip</button><button class="posclear" id="clearPosButton" type="button">入力クリア</button></div>`,
    `<div class="posSubBtns"><button class="postip" id="tipChangeButton" type="button">Tip</button><button class="postip" id="tipAmountButton" type="button">チップ指定</button><button class="posclear" id="clearPosButton" type="button">入力クリア</button></div>`
  );
  html = html.replace(`.posSubBtns{display:grid;grid-template-columns:1fr 1fr;gap:8px}`, `.posSubBtns{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}`);
  html = html.replace(`青・紫・緑系カードはアプリ売上入力用です。金種管理とは別で集計します。`, `ホームは当日、売上タブは月トータルで表示します。売上 = アプリ売上 + Tip / 利益 = 売上 − ガソリン代。`);

  const inject = `
<style>
#bottomNav{opacity:0!important;pointer-events:none!important;height:0!important;overflow:hidden!important;padding:0!important;border:0!important}
.cb-menu-button{position:fixed;left:12px;top:12px;z-index:90;width:42px;height:42px;border-radius:14px;border:1px solid #e5e7eb;background:#fff;color:#111827;font-size:22px;font-weight:950;box-shadow:0 8px 22px rgba(15,23,42,.10)}
.cb-menu-panel{position:fixed;left:12px;top:62px;z-index:91;width:min(280px,calc(100vw - 24px));background:#fff;border:1px solid #e5e7eb;border-radius:18px;box-shadow:0 20px 45px rgba(15,23,42,.18);padding:10px;display:none}.cb-menu-panel.open{display:block}.cb-menu-title{font-size:12px;color:#667085;font-weight:950;margin:4px 4px 8px}.cb-menu-grid{display:grid;gap:8px}.cb-menu-item{width:100%;border:1px solid #e5e7eb;border-radius:14px;background:#f8fafc;color:#111827;padding:12px;font-size:13px;font-weight:950;text-align:left}
.cb-custom-nav{position:fixed;left:50%;bottom:0;z-index:80;transform:translateX(-50%);width:min(1100px,100%);padding:8px 8px calc(8px + env(safe-area-inset-bottom,0px));background:rgba(255,255,255,.98);border-top:1px solid #e5e7eb;backdrop-filter:blur(16px)}
.cb-custom-nav-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.cb-nav-btn{border:1px solid #e5e7eb;border-radius:14px;background:#fff;color:#374151;padding:6px 1px;font-size:9.5px;font-weight:950;min-height:46px;line-height:1.1}.cb-nav-btn .ico{display:block;font-size:16px;margin-bottom:3px}.cb-nav-btn.active{background:#111827;color:#fff;border-color:#111827}.cb-menu-item:active,.cb-nav-btn:active,.cb-menu-button:active{transform:scale(.985)}
.analysis-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}@media(min-width:860px){.analysis-grid{grid-template-columns:repeat(4,1fr)}}
.cb-filter{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0 12px}.cb-filter label{font-size:11px;font-weight:950;color:#667085}.cb-filter select,.cb-filter input{width:100%;border:1px solid #e5e7eb;border-radius:12px;padding:10px;background:#fff;font-weight:800;color:#111827}.cb-filter .wide{grid-column:1/-1}.cb-filter button{width:100%;border:0;border-radius:14px;padding:12px;background:#111827;color:#fff;font-weight:950}
.cb-chart{margin-top:12px;border:1px solid #e5e7eb;border-radius:18px;padding:14px;background:#fff}.cb-chart-title{display:flex;justify-content:space-between;gap:10px;align-items:flex-end;margin-bottom:12px}.cb-chart-title h3{font-size:16px;margin:0;color:#111827}.cb-chart-title p{font-size:11px;margin:2px 0 0;color:#667085;font-weight:800}.cb-bars{display:grid;gap:10px}.cb-bar-row{display:grid;grid-template-columns:52px 1fr 72px;gap:8px;align-items:center}.cb-bar-label{font-size:11px;font-weight:950;color:#475467;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cb-bar-track{height:12px;background:#eef2f7;border-radius:999px;overflow:hidden}.cb-bar-fill{height:100%;border-radius:999px;background:#111827}.cb-bar-fill.soft{background:#0ea5e9}.cb-bar-value{text-align:right;font-size:11px;font-weight:950;color:#111827}.cb-empty{padding:18px;border:1px dashed #d0d5dd;border-radius:16px;color:#667085;font-size:13px;font-weight:800;text-align:center}.cb-analysis-note{font-size:13px;line-height:1.8;color:#344054}.cb-analysis-note ol{margin:0;padding-left:20px}body{padding-bottom:76px!important}
</style>
<script>
(function(){
'use strict';
var PINKEY='cash_balance_app_pin_v21',DRAFTKEY='cash_balance_app_draft_v21',API='/api/records';
var DENOMS=[10000,5000,2000,1000,500,100,50,10,5,1];
var START_DEFAULTS={10000:0,5000:1,2000:0,1000:10,500:8,100:15,50:10,10:15,5:10,1:15};
function yen(n){n=Math.round(Number(n||0));return '¥'+n.toLocaleString('ja-JP')}
function pct(n){return (Math.round(Number(n||0)*10)/10)+'%'}
function money(v){var n=Math.floor(Number(v||0));return Number.isFinite(n)&&n>0?n:0}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function parseDate(s){var p=String(s||today()).split('-').map(Number);return new Date(p[0]||new Date().getFullYear(),(p[1]||1)-1,p[2]||1)}
function sameDay(a,b){return String(a||'')===String(b||'')}
function sameMonth(a,b){var da=parseDate(a),db=parseDate(b);return da.getFullYear()===db.getFullYear()&&da.getMonth()===db.getMonth()}
function weekStart(d){var x=new Date(d);var diff=(x.getDay()+6)%7;x.setDate(x.getDate()-diff);x.setHours(0,0,0,0);return x}
function sameWeek(a,b){return weekStart(parseDate(a)).getTime()===weekStart(parseDate(b)).getTime()}
function monthStart(d){return new Date(d.getFullYear(),d.getMonth(),1)}
function monthEnd(d){return new Date(d.getFullYear(),d.getMonth()+1,0)}
function addDays(d,n){var x=new Date(d);x.setDate(x.getDate()+n);return x}
function monthLabel(s){var d=parseDate(s);return (d.getMonth()+1)+'月'}
function weekLabel(s){var d=weekStart(parseDate(s));return (d.getMonth()+1)+'/'+d.getDate()+'週'}
function dayLabel(s){var d=parseDate(s);return (d.getMonth()+1)+'/'+d.getDate()}
function draftState(){try{var raw=localStorage.getItem(DRAFTKEY);if(!raw)return null;var d=JSON.parse(raw);return d&&d.state?d.state:null}catch(e){return null}}
function currentState(){var s=JSON.parse(JSON.stringify(draftState()||{}));var v;v=document.getElementById('workDate');if(v)s.date=v.value||s.date||today();v=document.getElementById('startTime');if(v)s.startTime=v.value||'';v=document.getElementById('endTime');if(v)s.endTime=v.value||'';v=document.getElementById('dailySales');if(v)s.dailySales=money(v.value);v=document.getElementById('salesMemo');if(v)s.salesMemo=v.value||'';s.uberPending=0;if(!s.counts)s.counts={};return s}
function totalCounts(r,sec){var counts=r&&r.counts&&r.counts[sec]?r.counts[sec]:{};return DENOMS.reduce(function(sum,den){return sum+money(counts[String(den)])*den},0)}
function minutes(r){var s=r&&r.startTime,e=r&&r.endTime;if(!s||!e)return 0;var sp=String(s).split(':').map(Number),ep=String(e).split(':').map(Number);var sm=(sp[0]||0)*60+(sp[1]||0),em=(ep[0]||0)*60+(ep[1]||0);if(em<sm)em+=1440;return Math.max(0,em-sm)}
function calc(r){r=r||{};var pos=Array.isArray(r.posItems)?r.posItems:[],gasItems=Array.isArray(r.gasItems)?r.gasItems:[];var posSales=pos.reduce(function(s,x){return s+money(x.sale)},0),posTips=pos.reduce(function(s,x){return s+money(x.tip)},0),tips=posTips+totalCounts(r,'tips'),app=money(r.dailySales),gas=gasItems.reduce(function(s,x){return s+money(x.cost)},0);var sales=app+tips,profit=sales-gas,cashIn=posSales+tips;var expected=totalCounts(r,'start')+posSales+totalCounts(r,'received')+tips+totalCounts(r,'exchange')-gas;return{appSales:app,tips:tips,posSales:posSales,gas:gas,sales:sales,profit:profit,cashIn:cashIn,diff:totalCounts(r,'end')-expected,minutes:minutes(r),date:r.date||today()}}
function mergeCurrent(records){var cur=currentState(),out=Array.isArray(records)?records.slice():[];var idx=out.findIndex(function(r){return cur.id&&r.id===cur.id});if(idx>=0)out[idx]=cur;else out.push(cur);return out}
async function loadRecords(){var pin=localStorage.getItem(PINKEY)||'',d=draftState();if(!pin)return mergeCurrent(d?[d]:[]);try{var res=await fetch(API+'?limit=1000&ts='+Date.now(),{cache:'no-store',headers:{'x-app-pin':pin}});var data=await res.json();return mergeCurrent(Array.isArray(data.records)?data.records:[])}catch(e){return mergeCurrent(d?[d]:[])}}
function period(records,kind,base){var out={sales:0,profit:0,appSales:0,tips:0,gas:0,cashIn:0,diff:0,minutes:0,count:0,posSales:0,activeDays:0};var days={};records.forEach(function(r){var ok=kind==='day'?sameDay(r.date,base):kind==='week'?sameWeek(r.date,base):sameMonth(r.date,base);if(!ok)return;var c=calc(r);Object.keys(out).forEach(function(k){if(k!=='count'&&k!=='activeDays')out[k]+=c[k]||0});if((c.sales||c.minutes||c.gas||c.cashIn))days[r.date]=1;out.count++});out.activeDays=Object.keys(days).length;return out}
function sumRows(rows){var out={sales:0,profit:0,appSales:0,tips:0,gas:0,cashIn:0,diff:0,minutes:0,count:0,activeDays:0};var days={};rows.forEach(function(r){var c=calc(r);Object.keys(out).forEach(function(k){if(k!=='count'&&k!=='activeDays')out[k]+=c[k]||0});if((c.sales||c.minutes||c.gas||c.cashIn))days[r.date]=1;out.count++});out.activeDays=Object.keys(days).length;return out}
function filterRows(records,start,end){var st=parseDate(start),ed=parseDate(end);st.setHours(0,0,0,0);ed.setHours(23,59,59,999);return records.filter(function(r){var d=parseDate(r.date);return d>=st&&d<=ed})}
function card(label,value,sub,cls){return '<div class="salesCard '+(cls||'')+'"><div class="label">'+label+'</div><div class="value '+(value<0?'bad':'')+'">'+yen(value)+'</div><div class="sub">'+sub+'</div></div>'}
function textCard(label,value,sub,cls){return '<div class="salesCard '+(cls||'')+'"><div class="label">'+label+'</div><div class="value">'+value+'</div><div class="sub">'+sub+'</div></div>'}
function wage(profit,min){return{hourly:min>0?profit/(min/60):0,minutely:min>0?profit/min:0}}
async function renderDashboard(){var records=await loadRecords(),base=(document.getElementById('workDate')&&document.getElementById('workDate').value)||today();var d=period(records,'day',base),w=period(records,'week',base),m=period(records,'month',base),dw=wage(d.profit,d.minutes),mw=wage(m.profit,m.minutes);var home='';home+=card('今日の売上',d.sales,'アプリ売上 + Tip','');home+=card('今日の利益',d.profit,'売上 − ガソリン','profit');home+=card('今日の現金合計',d.cashIn,'POS現金 + Tip','');home+=card('今日の差異',d.diff,'終了時 − 理論上',d.diff===0?'profit':'');home+=card('時給',dw.hourly,'当日の利益 ÷ 稼働時間','profit');home+=card('分給',dw.minutely,'当日の稼働時間 '+d.minutes+'分','profit');var sales='';sales+=card('今月の売上',m.sales,'月トータル：アプリ売上 + Tip','month');sales+=card('今月の利益',m.profit,'月トータル：売上 − ガソリン','profit');sales+=card('今月の現金合計',m.cashIn,'月トータル：POS現金 + Tip','month');sales+=card('今月の差異合計',m.diff,'月トータル：終了時 − 理論上',m.diff===0?'profit':'');sales+=card('月トータル時給',mw.hourly,'今月の利益 ÷ 今月の稼働時間','profit');sales+=card('月トータル分給',mw.minutely,'今月の稼働時間 '+m.minutes+'分 / '+m.activeDays+'日','profit');sales+=card('今週の売上',w.sales,'参考：週トータル','');sales+=card('今週の利益',w.profit,'参考：週トータル','profit');var a=document.getElementById('salesDashboard'),b=document.getElementById('salesPeriodCards');if(a)a.innerHTML=home;if(b)b.innerHTML=sales;renderAnalysis(records,d,w,m,dw,mw)}
function amountText(t){return Number(String(t||'').replace(/[^0-9-]/g,'')||0)}function clickKey(k){var b=document.querySelector('.key[data-key="'+k+'"]');if(b)b.click()}function typeAmount(n){String(Math.max(0,Math.floor(Number(n||0)))).split('').forEach(function(ch){clickKey(ch)})}function setPaid(n){var p=document.querySelector('.modeBtn[data-mode="paid"]');if(p)p.click();clickKey('C');typeAmount(n)}
function manualTip(){var sale=amountText(document.getElementById('posSaleView')&&document.getElementById('posSaleView').textContent),paid=amountText(document.getElementById('posPaidView')&&document.getElementById('posPaidView').textContent),change=Math.max(0,paid-sale);if(!sale||!paid||change<=0){alert('チップ指定できるおつりがありません。');return}var input=prompt('何円チップにしますか？\\n現在のおつり：'+change.toLocaleString('ja-JP')+'円',change%1000||'');if(input===null)return;var tip=Math.floor(Number(String(input).replace(/[^0-9]/g,''))||0);if(tip<=0){alert('1円以上で入力してください。');return}if(tip>change){alert('チップはおつり以下で入力してください。');return}var btn=document.getElementById('tipChangeButton');if(!btn){alert('Tipボタンが見つかりません。');return}setPaid(sale+tip);setTimeout(function(){btn.click();setTimeout(function(){setPaid(paid);renderDashboard()},120)},120)}
function ensureTipButton(){var area=document.querySelector('.posSubBtns');if(!area)return;area.style.gridTemplateColumns='1fr 1fr 1fr';var old=document.getElementById('tipFractionButton');if(old)old.remove();var clear=document.getElementById('clearPosButton'),btn=document.getElementById('tipAmountButton');if(!btn){btn=document.createElement('button');btn.id='tipAmountButton';btn.type='button';btn.className='postip';btn.textContent='チップ指定';if(clear)area.insertBefore(btn,clear);else area.appendChild(btn)}btn.textContent='チップ指定';btn.onclick=manualTip}
function applyStartDefaults(){Object.keys(START_DEFAULTS).forEach(function(den){var input=document.getElementById('start-'+den);if(input){input.value=String(START_DEFAULTS[den]);input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}})}
function ensureDefaultButton(){var view=document.getElementById('view-start');if(!view||document.getElementById('start-default-cash-button'))return;var btn=document.createElement('button');btn.id='start-default-cash-button';btn.type='button';btn.className='btn lightbtn';btn.textContent='デフォルト値を反映';btn.style.margin='0 0 12px 0';btn.style.width='100%';btn.onclick=applyStartDefaults;var first=view.querySelector('.money')||view.querySelector('.mrow');if(first)first.insertAdjacentElement('beforebegin',btn);else view.prepend(btn)}
function hideUberField(){var input=document.getElementById('uberPending');if(!input)return;input.value='0';var wrap=input.closest('div');if(wrap&&wrap.querySelector('label'))wrap.style.display='none'}
function ensureAnalysisView(){var main=document.getElementById('mainArea');if(!main||document.getElementById('view-analysis'))return;var sec=document.createElement('section');sec.className='view';sec.id='view-analysis';sec.innerHTML='<section class="panel salesPanel"><div class="head"><div><h2>分析</h2><div class="help">期間を選ぶと、売上・稼働時間・時給・稼働日数がすぐ確認できます。</div></div></div><div class="cb-filter"><div><label>表示単位</label><select id="analysisUnit"><option value="day">日別</option><option value="week">週別</option><option value="month">月別</option></select></div><div><label>クイック期間</label><select id="analysisQuick"><option value="month">今月</option><option value="week">今週</option><option value="custom">任意期間</option></select></div><div><label>開始日</label><input id="analysisStart" type="date"></div><div><label>終了日</label><input id="analysisEnd" type="date"></div><div class="wide"><button id="analysisApply" type="button">分析を更新</button></div></div><div class="analysis-grid" id="analysisCards"></div><div id="analysisCharts"></div></section><section class="panel"><div class="head"><div><h2>分析メモ</h2></div></div><div class="hint cb-analysis-note" id="analysisMemo">データを入力すると分析が表示されます。</div></section>';main.appendChild(sec);var q=sec.querySelector('#analysisQuick'),st=sec.querySelector('#analysisStart'),ed=sec.querySelector('#analysisEnd');function setRange(){var now=parseDate(today());if(q.value==='week'){var ws=weekStart(now);st.value=iso(ws);ed.value=iso(addDays(ws,6))}else if(q.value==='month'){st.value=iso(monthStart(now));ed.value=iso(monthEnd(now))}}q.onchange=function(){setRange();renderDashboard()};sec.querySelector('#analysisUnit').onchange=renderDashboard;st.onchange=function(){q.value='custom';renderDashboard()};ed.onchange=function(){q.value='custom';renderDashboard()};sec.querySelector('#analysisApply').onclick=renderDashboard;setRange()}
function bucketKey(date,unit){var d=parseDate(date);if(unit==='month')return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');if(unit==='week'){var w=weekStart(d);return iso(w)}return iso(d)}
function bucketLabel(key,unit){if(unit==='month')return monthLabel(key+'-01');if(unit==='week')return weekLabel(key);return dayLabel(key)}
function makeBuckets(rows,unit){var map={};rows.forEach(function(r){var k=bucketKey(r.date,unit);if(!map[k])map[k]={key:k,label:bucketLabel(k,unit),sales:0,minutes:0,profit:0,gas:0,tips:0,days:{}};var c=calc(r);map[k].sales+=c.sales;map[k].minutes+=c.minutes;map[k].profit+=c.profit;map[k].gas+=c.gas;map[k].tips+=c.tips;if(c.sales||c.minutes||c.gas)map[k].days[r.date]=1});return Object.keys(map).sort().map(function(k){var x=map[k];x.activeDays=Object.keys(x.days).length;return x})}
function barChart(title,sub,rows,key,format,soft){if(!rows.length)return '<div class="cb-chart"><div class="cb-chart-title"><div><h3>'+title+'</h3><p>'+sub+'</p></div></div><div class="cb-empty">この期間のデータがありません。</div></div>';var max=Math.max(1,...rows.map(function(r){return r[key]}));return '<div class="cb-chart"><div class="cb-chart-title"><div><h3>'+title+'</h3><p>'+sub+'</p></div></div><div class="cb-bars">'+rows.map(function(r){var w=Math.max(3,Math.round((r[key]/max)*100));var val=format==='time'?(Math.round(r[key]/60*10)/10)+'h':yen(r[key]);return '<div class="cb-bar-row"><div class="cb-bar-label">'+r.label+'</div><div class="cb-bar-track"><div class="cb-bar-fill '+(soft?'soft':'')+'" style="width:'+w+'%"></div></div><div class="cb-bar-value">'+val+'</div></div>'}).join('')+'</div></div>'}
function renderAnalysis(records,d,w,m,dw,mw){ensureAnalysisView();var unitEl=document.getElementById('analysisUnit'),stEl=document.getElementById('analysisStart'),edEl=document.getElementById('analysisEnd');var unit=unitEl?unitEl.value:'day',start=stEl&&stEl.value?stEl.value:iso(monthStart(parseDate(today()))),end=edEl&&edEl.value?edEl.value:today();var rows=filterRows(records,start,end),sum=sumRows(rows),wg=wage(sum.profit,sum.minutes);var host=document.getElementById('analysisCards'),charts=document.getElementById('analysisCharts'),memo=document.getElementById('analysisMemo');if(!host)return;var gasRate=sum.sales>0?(sum.gas/sum.sales)*100:0,tipRate=sum.sales>0?(sum.tips/sum.sales)*100:0,cashRate=sum.sales>0?(sum.cashIn/sum.sales)*100:0;var html='';html+=card('期間売上',sum.sales,start+'〜'+end,'month');html+=card('期間利益',sum.profit,'売上 − ガソリン','profit');html+=textCard('稼働日数',sum.activeDays+'日','売上・時間・経費がある日','');html+=textCard('稼働時間',Math.round(sum.minutes/60*10)/10+'h','合計 '+sum.minutes+'分','');html+=card('時給',wg.hourly,'期間利益 ÷ 稼働時間','profit');html+=card('分給',wg.minutely,'期間利益 ÷ 稼働分数','profit');html+=textCard('ガソリン率',pct(gasRate),'ガソリン ÷ 売上','');html+=textCard('Tip率',pct(tipRate),'Tip ÷ 売上','');html+=textCard('現金比率',pct(cashRate),'現金合計 ÷ 売上','');html+=card('差異合計',sum.diff,'0円に近いほど良い',sum.diff===0?'profit':'');host.innerHTML=html;var buckets=makeBuckets(rows,unit);if(charts){charts.innerHTML=barChart('売上金額グラフ','選択期間の売上推移',buckets,'sales','money',false)+barChart('稼働時間グラフ','選択期間の稼働時間推移',buckets,'minutes','time',true)}if(memo){var notes=[];if(sum.activeDays===0)notes.push('この期間は稼働データがありません。期間を変更するか、売上・開始終了時刻を入力してください。');else notes.push('この期間は '+sum.activeDays+'日稼働、合計 '+Math.round(sum.minutes/60*10)/10+'時間です。');if(sum.minutes===0)notes.push('開始時刻・終了時刻を入れると、時給と稼働時間が正確に出ます。');if(gasRate>15)notes.push('ガソリン率が15%を超えています。移動距離や稼働エリアの見直し候補です。');if(sum.diff!==0)notes.push('差異が '+yen(sum.diff)+' 出ています。終了時現金・チップ・ガソリン入力を確認してください。');if(wg.hourly>0)notes.push('期間時給は '+yen(wg.hourly)+'、分給は '+yen(wg.minutely)+' です。');memo.innerHTML='<ol><li>'+notes.join('</li><li>')+'</li></ol>'}}
function ensureCustomNav(){if(!document.getElementById('cb-custom-nav')){var nav=document.createElement('nav');nav.id='cb-custom-nav';nav.className='cb-custom-nav';nav.innerHTML='<div class="cb-custom-nav-grid"><button class="cb-nav-btn active" data-cb-view="home"><span class="ico">⌂</span>ホーム</button><button class="cb-nav-btn" data-cb-view="start"><span class="ico">💴</span>開始時</button><button class="cb-nav-btn" data-cb-view="pos"><span class="ico">🧾</span>POS</button><button class="cb-nav-btn" data-cb-view="sales"><span class="ico">📊</span>売上</button><button class="cb-nav-btn" data-cb-view="gas"><span class="ico">⛽</span>ガソリン</button><button class="cb-nav-btn" data-cb-view="end"><span class="ico">✓</span>終了時</button><button class="cb-nav-btn" data-cb-view="analysis"><span class="ico">▦</span>分析</button></div>';document.body.appendChild(nav);nav.addEventListener('click',function(e){var btn=e.target.closest('[data-cb-view]');if(btn)openCustomView(btn.dataset.cbView)})}if(!document.getElementById('cb-menu-button')){var b=document.createElement('button');b.id='cb-menu-button';b.className='cb-menu-button';b.type='button';b.textContent='☰';document.body.appendChild(b);var p=document.createElement('div');p.id='cb-menu-panel';p.className='cb-menu-panel';p.innerHTML='<div class="cb-menu-title">その他メニュー</div><div class="cb-menu-grid"><button class="cb-menu-item" data-cb-view="received">受取金</button><button class="cb-menu-item" data-cb-view="tips">チップ</button><button class="cb-menu-item" data-cb-view="exchange">両替</button><button class="cb-menu-item" data-cb-action="reload">最新読込</button><button class="cb-menu-item" data-cb-action="json">JSON出力</button><button class="cb-menu-item" data-cb-action="csv">CSV出力</button><button class="cb-menu-item" data-cb-action="logout">ログアウト</button></div>';document.body.appendChild(p);b.onclick=function(){p.classList.toggle('open')};p.addEventListener('click',function(e){var item=e.target.closest('.cb-menu-item');if(!item)return;p.classList.remove('open');if(item.dataset.cbAction){var map={reload:'reloadButton',json:'jsonButton',csv:'csvButton',logout:'logoutButton'};var el=document.getElementById(map[item.dataset.cbAction]);if(el)el.click();return}openCustomView(item.dataset.cbView)})}}
function setCustomActive(view){document.querySelectorAll('.cb-nav-btn').forEach(function(b){b.classList.toggle('active',b.dataset.cbView===view)})}
function openCustomView(view){ensureAnalysisView();if(view==='analysis'){document.querySelectorAll('.view').forEach(function(v){v.classList.remove('active')});var a=document.getElementById('view-analysis');if(a)a.classList.add('active');document.body.classList.remove('pos-active');setCustomActive('analysis');renderDashboard();return}var original=document.querySelector('#bottomNav .navbtn[data-view="'+view+'"]');if(original)original.click();setTimeout(function(){setCustomActive(view);renderDashboard()},80)}
function syncCustomNavVisibility(){var main=document.getElementById('mainArea');var loggedIn=main&&!main.classList.contains('hidden');['cb-custom-nav','cb-menu-button'].forEach(function(id){var el=document.getElementById(id);if(el)el.style.display=loggedIn?'':'none'});var panel=document.getElementById('cb-menu-panel');if(panel&&!loggedIn)panel.classList.remove('open')}
function run(){ensureCustomNav();ensureAnalysisView();ensureTipButton();ensureDefaultButton();hideUberField();syncCustomNavVisibility();renderDashboard()}
var timer=null;var obs=new MutationObserver(function(){clearTimeout(timer);timer=setTimeout(run,180)});window.addEventListener('DOMContentLoaded',function(){run();if(document.body)obs.observe(document.body,{childList:true,subtree:true});['input','change','click'].forEach(function(ev){document.addEventListener(ev,function(){clearTimeout(timer);timer=setTimeout(run,220)},true)});setTimeout(run,500);setTimeout(run,1500)})
})();
</script>
`;

  html = html.replace("</body>", inject + "</body>");
  return new Response(html, response);
}
