export async function onRequest(context) {
  const response = await context.next();
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("text/html")) return response;

  let html = await response.text();
  html = html.replace(`.posSubBtns{display:grid;grid-template-columns:1fr 1fr;gap:8px}`, `.posSubBtns{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px}`);
  html = html.replace('理論上の終了金額 = 開始時 + 現金売上 + 両替 − ガソリン − Uber調整。','理論上の終了金額 = 開始時 + 現金売上 + 両替 − ガソリン − 銀行入金。');

  const inject = `
<style>
#bottomNav{opacity:0!important;pointer-events:none!important;height:0!important;overflow:hidden!important;padding:0!important;border:0!important}
body.cb-analysis-active .bottomsum{display:none!important}
.cb-menu-button{position:fixed;left:12px;top:76px;z-index:90;width:42px;height:42px;border-radius:14px;border:1px solid #e5e7eb;background:#fff;color:#111827;font-size:22px;font-weight:950;box-shadow:0 8px 22px rgba(15,23,42,.10)}
body.pos-active .cb-menu-button{top:70px}.cb-menu-panel{position:fixed;left:12px;top:124px;z-index:91;width:min(280px,calc(100vw - 24px));background:#fff;border:1px solid #e5e7eb;border-radius:18px;box-shadow:0 20px 45px rgba(15,23,42,.18);padding:10px;display:none}.cb-menu-panel.open{display:block}.cb-menu-item{width:100%;border:1px solid #e5e7eb;border-radius:14px;background:#f8fafc;color:#111827;padding:12px;font-size:13px;font-weight:950;text-align:left;margin-top:7px}
.cb-custom-nav{position:fixed;left:50%;bottom:0;z-index:80;transform:translateX(-50%);width:min(1100px,100%);padding:8px 8px calc(8px + env(safe-area-inset-bottom,0px));background:rgba(255,255,255,.98);border-top:1px solid #e5e7eb;backdrop-filter:blur(16px)}.cb-custom-nav-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:5px}.cb-nav-btn{border:1px solid #e5e7eb;border-radius:14px;background:#fff;color:#374151;padding:6px 1px;font-size:9.5px;font-weight:950;min-height:46px;line-height:1.1}.cb-nav-btn .ico{display:block;font-size:16px;margin-bottom:3px}.cb-nav-btn.active{background:#111827;color:#fff;border-color:#111827}body{padding-bottom:76px!important}.analysis-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.cb-filter{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0 12px}.cb-filter label{font-size:11px;font-weight:950;color:#667085}.cb-filter input,.cb-filter select{border:1px solid #e5e7eb;border-radius:12px;padding:10px;background:#fff;font-weight:800}.cb-filter button{grid-column:1/-1;border-radius:14px;padding:12px;background:#111827;color:#fff;font-weight:950}.cb-chart{margin-top:12px;border:1px solid #e5e7eb;border-radius:18px;padding:14px;background:#fff}.cb-combo-svg{min-width:760px;width:760px;height:280px}.cb-combo-wrap{overflow-x:auto}.cb-analysis-note{font-size:13px;line-height:1.8;color:#344054}.cb-analysis-note ol{margin:0;padding-left:20px}.cb-legend{display:flex;gap:12px;flex-wrap:wrap;margin:8px 0 0;font-size:12px;font-weight:900;color:#475467}.cb-dot{display:inline-block;width:10px;height:10px;border-radius:999px;margin-right:4px}.cb-dot.sales{background:#111827}.cb-dot.profit{background:#0ea5e9}.cb-compare{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.cb-compare .salesCard{min-height:74px}.cb-weekday{margin-top:12px;border:1px solid #e5e7eb;border-radius:18px;background:#fff;padding:14px}.cb-weekday h3{margin:0 0 10px;font-size:16px}.cb-weekday-row{display:grid;grid-template-columns:52px 1fr 1fr;gap:8px;border-top:1px solid #eef2f7;padding:10px 0;font-size:12px;align-items:center}.cb-weekday-row:first-of-type{border-top:0}.cb-weekday-row b{font-size:14px}.cb-weekday-row .num{font-weight:950;text-align:right}.cb-weekday-row .sub{color:#667085;font-size:11px;text-align:right}.cb-history-month summary{list-style:none}.cb-history-month summary::-webkit-details-marker{display:none}.cb-history-month .list{margin-top:10px}
</style>
<script>
(function(){
'use strict';
var PINKEY='cash_balance_app_pin_v21',DRAFTKEY='cash_balance_app_draft_v21',API='/api/records';
var DENOMS=[10000,5000,2000,1000,500,100,50,10,5,1];
function yen(n){n=Math.round(Number(n||0));return '¥'+n.toLocaleString('ja-JP')}
function money(v){var n=Math.floor(Number(v||0));return Number.isFinite(n)&&n>0?n:0}
function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function nowHM(){var d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function parseDate(s){var p=String(s||today()).slice(0,10).split('-').map(Number);return new Date(p[0]||new Date().getFullYear(),(p[1]||1)-1,p[2]||1)}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function monthStart(d){return new Date(d.getFullYear(),d.getMonth(),1)}
function monthEnd(d){return new Date(d.getFullYear(),d.getMonth()+1,0)}
function addDays(d,n){var x=new Date(d);x.setDate(x.getDate()+n);return x}
function weekStart(d){var x=new Date(d),diff=(x.getDay()+6)%7;x.setDate(x.getDate()-diff);x.setHours(0,0,0,0);return x}
function getDraft(){try{return JSON.parse(localStorage.getItem(DRAFTKEY)||'{}')||{}}catch(e){return{}}}
function defaultCounts(){var sections=['start','received','tips','exchange','end'],c={};sections.forEach(function(s){c[s]={};DENOMS.forEach(function(d){c[s][String(d)]=0})});return c}
function stateFromDraft(){var box=getDraft(),s=box.state||{};if(!s.id)s.id='rec_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);if(!s.date)s.date=(document.getElementById('workDate')&&document.getElementById('workDate').value)||today();if(!s.counts)s.counts=defaultCounts();if(!Array.isArray(s.posItems))s.posItems=[];if(!Array.isArray(s.gasItems))s.gasItems=[];var ds=document.getElementById('dailySales');if(ds)s.dailySales=money(ds.value);return s}
function amountText(t){return Number(String(t||'').replace(/[^0-9-]/g,'')||0)}
async function saveRecord(s){var pin=localStorage.getItem(PINKEY)||'';if(!pin)return;try{await fetch(API,{method:'POST',cache:'no-store',headers:{'content-type':'application/json','x-app-pin':pin},body:JSON.stringify({record:s})})}catch(e){}}
async function manualTip(){var sale=amountText(document.getElementById('posSaleView')&&document.getElementById('posSaleView').textContent);var paid=amountText(document.getElementById('posPaidView')&&document.getElementById('posPaidView').textContent);var change=Math.max(0,paid-sale);if(!sale||!paid||change<=0){alert('チップ指定できるおつりがありません。');return}var input=prompt('何円チップにしますか？'+String.fromCharCode(10)+'現在のおつり：'+change.toLocaleString('ja-JP')+'円',change%1000||'');if(input===null)return;var tip=Math.floor(Number(String(input).replace(/[^0-9]/g,''))||0);if(tip<=0){alert('1円以上で入力してください。');return}if(tip>change){alert('チップはおつり以下で入力してください。');return}var remain=change-tip;var s=stateFromDraft(),memo=(document.getElementById('posMemo')&&document.getElementById('posMemo').value)||'';var now=new Date().toISOString();if(!s.createdAt)s.createdAt=now;s.updatedAt=now;s.posItems.push({id:'pos_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),sale:sale,paid:paid,change:remain,tip:tip,memo:memo,time:nowHM(),createdAt:now});var box=getDraft();box.state=s;box.pos={mode:'sale',sale:'',paid:'',memo:'',tip:0};box.currentView='pos';box.updatedAt=now;localStorage.setItem(DRAFTKEY,JSON.stringify(box));await saveRecord(s);alert('登録しました：チップ '+yen(tip)+' / おつり '+yen(remain));location.reload()}
function ensureTipButton(){var area=document.querySelector('.posSubBtns');if(!area)return;area.style.gridTemplateColumns='1fr 1fr 1fr';var old=document.getElementById('tipFractionButton');if(old)old.remove();var clear=document.getElementById('clearPosButton'),btn=document.getElementById('tipAmountButton');if(!btn){btn=document.createElement('button');btn.id='tipAmountButton';btn.type='button';btn.className='postip';btn.textContent='チップ指定';if(clear)area.insertBefore(btn,clear);else area.appendChild(btn)}btn.textContent='チップ指定';btn.onclick=function(e){e.preventDefault();e.stopPropagation();manualTip()}}
function ensureDefaultButton(){var view=document.getElementById('view-start');if(!view||document.getElementById('start-default-cash-button'))return;var defaults={10000:0,5000:1,2000:0,1000:10,500:8,100:15,50:10,10:15,5:10,1:15};var btn=document.createElement('button');btn.id='start-default-cash-button';btn.type='button';btn.className='btn lightbtn';btn.textContent='デフォルト値を反映';btn.style.cssText='width:100%;margin:0 0 12px';btn.onclick=function(){Object.keys(defaults).forEach(function(d){var i=document.getElementById('start-'+d);if(i){i.value=defaults[d];i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}))}})};var first=view.querySelector('.money')||view.querySelector('.mrow');if(first)first.insertAdjacentElement('beforebegin',btn);else view.prepend(btn)}
function openView(v){document.body.classList.toggle('cb-analysis-active',v==='analysis');if(v==='analysis'){ensureAnalysis();document.querySelectorAll('.view').forEach(function(x){x.classList.remove('active')});document.getElementById('view-analysis').classList.add('active');setActive(v);renderAnalysis();return}var b=document.querySelector('#bottomNav .navbtn[data-view="'+v+'"]');if(b)b.click();setActive(v)}
function setActive(v){document.querySelectorAll('.cb-nav-btn').forEach(function(b){b.classList.toggle('active',b.dataset.cbView===v)})}
function ensureNav(){if(!document.getElementById('cb-custom-nav')){var nav=document.createElement('nav');nav.id='cb-custom-nav';nav.className='cb-custom-nav';nav.innerHTML='<div class="cb-custom-nav-grid"><button class="cb-nav-btn active" data-cb-view="home"><span class="ico">⌂</span>ホーム</button><button class="cb-nav-btn" data-cb-view="start"><span class="ico">💴</span>開始時</button><button class="cb-nav-btn" data-cb-view="pos"><span class="ico">🧾</span>POS</button><button class="cb-nav-btn" data-cb-view="sales"><span class="ico">📊</span>売上</button><button class="cb-nav-btn" data-cb-view="end"><span class="ico">✓</span>終了時</button><button class="cb-nav-btn" data-cb-view="analysis"><span class="ico">▦</span>分析</button></div>';document.body.appendChild(nav);nav.onclick=function(e){var b=e.target.closest('[data-cb-view]');if(b)openView(b.dataset.cbView)}}if(!document.getElementById('cb-menu-button')){var mb=document.createElement('button');mb.id='cb-menu-button';mb.className='cb-menu-button';mb.type='button';mb.textContent='☰';document.body.appendChild(mb);var p=document.createElement('div');p.id='cb-menu-panel';p.className='cb-menu-panel';p.innerHTML='<button class="cb-menu-item" data-v="received">受取金</button><button class="cb-menu-item" data-v="tips">チップ</button><button class="cb-menu-item" data-v="exchange">両替</button><button class="cb-menu-item" data-v="gas">ガソリン</button><button class="cb-menu-item" data-a="reloadButton">最新読込</button><button class="cb-menu-item" data-a="logoutButton">ログアウト</button>';document.body.appendChild(p);mb.onclick=function(){p.classList.toggle('open')};p.onclick=function(e){var it=e.target.closest('.cb-menu-item');if(!it)return;p.classList.remove('open');if(it.dataset.v)openView(it.dataset.v);if(it.dataset.a){var x=document.getElementById(it.dataset.a);if(x)x.click()}}}}
function totalCounts(s,sec){var c=s.counts&&s.counts[sec]?s.counts[sec]:{};return DENOMS.reduce(function(sum,d){return sum+money(c[String(d)])*d},0)}
function mins(s){var a=s.startTime,b=s.endTime;if(!a||!b)return 0;var x=String(a).split(':').map(Number),y=String(b).split(':').map(Number),m1=(x[0]||0)*60+(x[1]||0),m2=(y[0]||0)*60+(y[1]||0);if(m2<m1)m2+=1440;return Math.max(0,m2-m1)}
function calc(s){s=s||{};var pos=Array.isArray(s.posItems)?s.posItems:[],gas=Array.isArray(s.gasItems)?s.gasItems:[];var ps=pos.reduce(function(a,x){return a+money(x.sale)},0),tip=pos.reduce(function(a,x){return a+money(x.tip)},0)+totalCounts(s,'tips'),gc=gas.reduce(function(a,x){return a+money(x.cost)},0),app=money(s.dailySales);return{date:(s.date||today()).slice(0,10),sales:app+tip,profit:app+tip-gc,cash:ps+tip,gas:gc,tips:tip,minutes:mins(s)}}
async function loadRecords(){var pin=localStorage.getItem(PINKEY)||'',cur=stateFromDraft();if(!pin)return [cur];try{var r=await fetch(API+'?limit=5000&ts='+Date.now(),{cache:'no-store',headers:{'x-app-pin':pin}});var d=await r.json();var rows=Array.isArray(d.records)?d.records:[];if(cur&&cur.id){var i=rows.findIndex(function(x){return x.id===cur.id});if(i>=0)rows[i]=cur;else rows.push(cur)}return rows}catch(e){return [cur]}}
function rangeOf(kind){var n=parseDate(today());if(kind==='lastMonth'){var lm=new Date(n.getFullYear(),n.getMonth()-1,1);return{start:iso(monthStart(lm)),end:iso(monthEnd(lm))}}if(kind==='week'){var ws=weekStart(n);return{start:iso(ws),end:iso(addDays(ws,6))}}if(kind==='all')return{start:'1900-01-01',end:'2999-12-31'};return{start:iso(monthStart(n)),end:iso(monthEnd(n))}}
function prevRange(start,end){var s=parseDate(start),e=parseDate(end),days=Math.round((e-s)/86400000)+1;return{start:iso(addDays(s,-days)),end:iso(addDays(s,-1))}}
function inRange(c,start,end){var d=parseDate(c.date),s=parseDate(start),e=parseDate(end);s.setHours(0,0,0,0);e.setHours(23,59,59,999);return d>=s&&d<=e}
function sumRows(rows){var out={sales:0,profit:0,cash:0,gas:0,tips:0,minutes:0,days:0},used={};rows.forEach(function(r){var c=calc(r);out.sales+=c.sales;out.profit+=c.profit;out.cash+=c.cash;out.gas+=c.gas;out.tips+=c.tips;out.minutes+=c.minutes;if(c.sales||c.profit||c.gas||c.cash||c.minutes)used[c.date]=1});out.days=Object.keys(used).length;return out}
function card(label,val,sub,cls){return '<div class="salesCard '+(cls||'')+'"><div class="label">'+label+'</div><div class="value '+(Number(val)<0?'bad':'')+'">'+yen(val)+'</div><div class="sub">'+(sub||'')+'</div></div>'}
function txtCard(label,val,sub){return '<div class="salesCard"><div class="label">'+label+'</div><div class="value">'+val+'</div><div class="sub">'+(sub||'')+'</div></div>'}
function chart(rows){var cs=rows.map(calc).filter(function(c){return c.sales||c.profit||c.gas||c.minutes}).sort(function(a,b){return a.date.localeCompare(b.date)});if(!cs.length)return '<div class="cb-chart"><b>売上・利益グラフ</b><div class="empty">この期間のデータがありません</div></div>';var w=Math.max(760,80+cs.length*64),h=280,base=220,max=Math.max(1,...cs.map(function(c){return Math.max(c.sales,Math.abs(c.profit))})),pts=[];var html='<div class="cb-chart"><b>売上・利益グラフ</b><div class="cb-legend"><span><i class="cb-dot sales"></i>棒＝売上</span><span><i class="cb-dot profit"></i>線＝利益</span></div><div class="cb-combo-wrap"><svg class="cb-combo-svg" style="width:'+w+'px" viewBox="0 0 '+w+' '+h+'">';html+='<line x1="44" y1="'+base+'" x2="'+(w-20)+'" y2="'+base+'" stroke="#d0d5dd"/>';cs.forEach(function(c,i){var x=60+i*64,bh=Math.max(2,c.sales/max*150),y=base-bh,py=base-(c.profit/max*150);html+='<rect x="'+x+'" y="'+y+'" width="28" height="'+bh+'" rx="6" fill="#111827"><title>'+c.date+' 売上 '+yen(c.sales)+'</title></rect>';pts.push((x+14)+','+py);html+='<text x="'+(x+14)+'" y="250" font-size="11" text-anchor="middle" fill="#667085">'+c.date.slice(5).replace('-','/')+'</text>'});html+='<polyline points="'+pts.join(' ')+'" fill="none" stroke="#0ea5e9" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/>';html+='</svg></div></div>';return html}
function weekdayTable(rows){var names=['日','月','火','水','木','金','土'],map={};names.forEach(function(n,i){map[i]={name:n,sales:0,profit:0,days:{}}});rows.forEach(function(r){var c=calc(r),d=parseDate(c.date),w=d.getDay();map[w].sales+=c.sales;map[w].profit+=c.profit;if(c.sales||c.profit||c.gas||c.cash||c.minutes)map[w].days[c.date]=1});var arr=Object.keys(map).map(function(k){var x=map[k];x.count=Object.keys(x.days).length;x.avg=x.count?x.profit/x.count:0;return x});arr.sort(function(a,b){return b.avg-a.avg});var html='<div class="cb-weekday"><h3>曜日別分析</h3>';html+=arr.map(function(x){return '<div class="cb-weekday-row"><b>'+x.name+'曜</b><div><div class="num">利益 '+yen(x.profit)+'</div><div class="sub">稼働 '+x.count+'日</div></div><div><div class="num">平均 '+yen(x.avg)+'</div><div class="sub">売上 '+yen(x.sales)+'</div></div></div>'}).join('');html+='</div>';return html}
function historyKey(item){var el=item&&item.querySelector&&item.querySelector('.date');var t=el?String(el.textContent||''):'';var m=t.match(/(\d{4})年\s*(\d{1,2})月/);if(m)return m[1]+'-'+String(m[2]).padStart(2,'0');m=t.match(/(\d{4})-(\d{1,2})-/);if(m)return m[1]+'-'+String(m[2]).padStart(2,'0');return ''}
function foldHistory(){var host=document.getElementById('salesHistoryList')||document.getElementById('historyList');if(!host||host.dataset.cbBusy==='1'||host.querySelector('details.cb-history-month'))return;var items=Array.prototype.slice.call(host.children).filter(function(x){return historyKey(x)});if(items.length<2)return;var current=today().slice(0,7),groups={};items.forEach(function(item){var k=historyKey(item);(groups[k]||(groups[k]=[])).push(item)});var keys=Object.keys(groups).sort().reverse();host.dataset.cbBusy='1';host.innerHTML='';keys.forEach(function(k){var d=document.createElement('details');d.className='cb-history-month';if(k===current)d.open=true;var s=document.createElement('summary');s.className='item';s.innerHTML='<div class="itemMain"><div class="date">'+k.replace('-','年')+'月</div><div class="row2"><span class="badge ok">'+groups[k].length+'件</span></div></div>';var list=document.createElement('div');list.className='list';groups[k].forEach(function(item){item.style.display='';list.appendChild(item)});d.appendChild(s);d.appendChild(list);host.appendChild(d)});setTimeout(function(){delete host.dataset.cbBusy},0)}
function ensureAnalysis(){if(document.getElementById('view-analysis'))return;var main=document.getElementById('mainArea');if(!main)return;var sec=document.createElement('section');sec.className='view';sec.id='view-analysis';sec.innerHTML='<section class="panel salesPanel"><div class="head"><div><h2>分析</h2><div class="help">期間ごとの売上・利益・効率を確認できます。</div></div></div><div class="cb-filter"><div><label>期間</label><select id="analysisQuick"><option value="month">今月</option><option value="lastMonth">先月</option><option value="week">今週</option><option value="all">全期間</option><option value="custom">任意期間</option></select></div><div><label>開始日</label><input id="analysisStart" type="date"></div><div><label>終了日</label><input id="analysisEnd" type="date"></div><button id="analysisApply" type="button">分析を更新</button></div><div class="analysis-grid" id="analysisCards"></div><div id="analysisCompare"></div><div id="analysisCharts"></div><div id="analysisWeekday"></div></section><section class="panel"><div class="head"><div><h2>分析メモ</h2></div></div><div class="hint cb-analysis-note" id="analysisMemo"></div></section>';main.appendChild(sec);var q=sec.querySelector('#analysisQuick'),st=sec.querySelector('#analysisStart'),ed=sec.querySelector('#analysisEnd');function setR(){var r=rangeOf(q.value);if(q.value!=='custom'){st.value=r.start;ed.value=r.end}}q.onchange=function(){setR();renderAnalysis()};st.onchange=function(){q.value='custom'};ed.onchange=function(){q.value='custom'};sec.querySelector('#analysisApply').onclick=renderAnalysis;setR()}
async function renderAnalysis(){ensureAnalysis();var q=document.getElementById('analysisQuick'),st=document.getElementById('analysisStart'),ed=document.getElementById('analysisEnd'),r=rangeOf(q?q.value:'month');var start=st&&st.value?st.value:r.start,end=ed&&ed.value?ed.value:r.end;var records=await loadRecords(),rows=records.filter(function(x){return inRange(calc(x),start,end)}),sum=sumRows(rows),pr=prevRange(start,end),prev=sumRows(records.filter(function(x){return inRange(calc(x),pr.start,pr.end)}));var avg=sum.days?sum.profit/sum.days:0,hour=sum.minutes?sum.profit/(sum.minutes/60):0,min=sum.minutes?sum.profit/sum.minutes:0;var cards=document.getElementById('analysisCards'),comp=document.getElementById('analysisCompare'),charts=document.getElementById('analysisCharts'),week=document.getElementById('analysisWeekday'),memo=document.getElementById('analysisMemo');if(cards)cards.innerHTML=card('売上',sum.sales,start+'〜'+end,'month')+card('利益',sum.profit,'売上 − 経費','profit')+card('経費',sum.gas,'ガソリン代')+card('現金',sum.cash,'POS現金 + Tip')+card('チップ合計',sum.tips,'選択期間の合計')+txtCard('稼働日数',sum.days+'日','入力がある日')+card('平均日給',avg,'利益 ÷ 稼働日数','profit')+card('時給',hour,'利益 ÷ 稼働時間','profit')+card('分給',min,'利益 ÷ 稼働分数','profit');if(comp){var ds=sum.sales-prev.sales,dp=sum.profit-prev.profit;comp.innerHTML='<div class="cb-compare">'+card('前期間比 売上',ds,'前期間 '+yen(prev.sales),ds>=0?'profit':'')+card('前期間比 利益',dp,'前期間 '+yen(prev.profit),dp>=0?'profit':'')+'</div>'}if(charts)charts.innerHTML=chart(rows);if(week)week.innerHTML=weekdayTable(rows);if(memo){var rate=sum.sales?Math.round(sum.profit/sum.sales*1000)/10:0,gasRate=sum.sales?Math.round(sum.gas/sum.sales*1000)/10:0,notes=[],best='';var wd=document.querySelector('#analysisWeekday .cb-weekday-row b');if(wd)best=wd.textContent;notes.push('利益率は '+rate+'% です。');notes.push('経費率は '+gasRate+'% です。');if(sum.days)notes.push('平均日給は '+yen(avg)+'、時給は '+yen(hour)+'、分給は '+yen(min)+' です。');if(best)notes.push('この期間で平均利益が高い曜日は '+best+' です。');if(dp<0)notes.push('前期間より利益が下がっています。稼働時間、ガソリン代、売上単価を確認してください。');else notes.push('前期間より利益は改善しています。');memo.innerHTML='<ol><li>'+notes.join('</li><li>')+'</li></ol>'}}
function ensureBankDeposit(){var input=document.getElementById('uberPending'),view=document.getElementById('view-exchange');if(!input||!view)return;var oldWrap=input.closest('div');if(!oldWrap)return;var oldPanel=document.getElementById('bankDepositPanel');if(!oldPanel){var panel=document.createElement('section');panel.className='panel';panel.id='bankDepositPanel';panel.innerHTML='<div class="head"><div><h2>銀行入金</h2><div class="help">Uber Eatsへ送金するため銀行へ入金した現金を入力します。入力額は理論上の手元現金から差し引かれます。</div></div><div class="total" id="bankDepositPreview">¥0</div></div><div id="bankDepositField"></div>';view.appendChild(panel);oldPanel=panel}var field=oldPanel.querySelector('#bankDepositField');if(field&&oldWrap.parentElement!==field)field.appendChild(oldWrap);oldWrap.style.display='';var label=oldWrap.querySelector('label');if(label)label.textContent='銀行へ入金した金額';input.placeholder='例：10000';input.min='0';input.inputMode='numeric';function preview(){var p=document.getElementById('bankDepositPreview');if(p)p.textContent=yen(money(input.value))}if(!input.dataset.cbBankBound){input.dataset.cbBankBound='1';input.addEventListener('input',preview);input.addEventListener('change',preview)}preview()}
function syncVis(){var main=document.getElementById('mainArea'),ok=main&&!main.classList.contains('hidden');['cb-custom-nav','cb-menu-button'].forEach(function(id){var e=document.getElementById(id);if(e)e.style.display=ok?'':'none'})}
function run(){ensureNav();ensureTipButton();ensureDefaultButton();ensureAnalysis();foldHistory();ensureBankDeposit();syncVis()}
var t=null,obs=new MutationObserver(function(){clearTimeout(t);t=setTimeout(run,120)});window.addEventListener('DOMContentLoaded',function(){run();if(document.body)obs.observe(document.body,{childList:true,subtree:true});setTimeout(run,500);setTimeout(run,1500)})
})();
</script>`;

  html = html.replace("</body>", inject + "</body>");
  return new Response(html, response);
}
