(function(){
'use strict';
var DRAFTKEY='cash_balance_app_draft_v21',PINKEY='cash_balance_app_pin_v21',API='/api/records';
var TYPES={clockIn:{label:'出勤',ico:'▶'},clockOut:{label:'退勤',ico:'■'},breakStart:{label:'休憩',ico:'☕'},breakEnd:{label:'休憩終了',ico:'▶'}};
var syncBusy=false,syncPending=false;
function readBox(){try{return JSON.parse(localStorage.getItem(DRAFTKEY)||'{}')||{}}catch(e){return{}}}
function state(){var b=readBox();return b&&b.state?b.state:null}
function pad(n){return String(n).padStart(2,'0')}
function localParts(d){d=d||new Date();return {date:d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate()),time:pad(d.getHours())+':'+pad(d.getMinutes()),iso:d.toISOString()}}
function logs(s){return Array.isArray(s&&s.attendanceLogs)?s.attendanceLogs:[]}
function validNext(s,type){var k=status(s).key;if(type==='clockIn')return k==='off';if(type==='breakStart')return k==='work';if(type==='breakEnd')return k==='break';if(type==='clockOut')return k==='work'||k==='break';return false}
function toast(msg){var x=document.getElementById('attToast');if(!x){x=document.createElement('div');x.id='attToast';x.style.cssText='position:fixed;left:50%;bottom:90px;transform:translateX(-50%);z-index:9999;background:#111827;color:#fff;padding:10px 16px;border-radius:999px;font-weight:900;font-size:13px;box-shadow:0 8px 24px rgba(0,0,0,.18)';document.body.appendChild(x)}x.textContent=msg;x.style.display='block';clearTimeout(window.__attToastTimer);window.__attToastTimer=setTimeout(function(){x.style.display='none'},1800)}
function saveState(s){var b=readBox();if(!b.state)return;s.updatedAt=new Date().toISOString();b.state=s;b.updatedAt=s.updatedAt;localStorage.setItem(DRAFTKEY,JSON.stringify(b))}
function setSync(text,ok){var els=document.querySelectorAll('.att-sync');els.forEach(function(el){el.textContent=text;el.style.color=ok?'#047857':'#b45309'})}
async function syncD1(){var s=state();if(!s||!s.id){setSync('未送信',false);return false}var box={};try{box=JSON.parse(localStorage.getItem('cash_balance_app_save_outbox_v1')||'{}')||{}}catch(e){}var pending=!!box[String(s.id)];setSync(pending?'保存待ち・自動再送':'保存済み',!pending);return !pending}
function persist(s,msg){saveState(s);setSync('保存待ち…',false);setTimeout(syncD1,400);toast(msg)}
function add(type){var s=state();if(!s)return;if(!validNext(s,type)){toast('現在の状態では「'+(TYPES[type]?TYPES[type].label:type)+'」は記録できません');return}var p=localParts();var a=logs(s).slice();a.push({id:'att_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),type:type,date:p.date,time:p.time,createdAt:p.iso});s.attendanceLogs=a;persist(s,(TYPES[type]?TYPES[type].label:type)+' '+p.date+' '+p.time+' を保存しました');render()}
function status(s){var a=logs(s).slice().sort(function(x,y){return String(x.date||'')+String(x.time||'')>String(y.date||'')+String(y.time||'')?1:-1}),last=a[a.length-1];if(!last)return{key:'off',label:'未出勤'};if(last.type==='clockOut')return{key:'off',label:'退勤済み'};if(last.type==='breakStart')return{key:'break',label:'休憩中'};return{key:'work',label:'勤務中'}}
function mins(s){var a=logs(s).slice().sort(function(x,y){return (x.date+'T'+x.time).localeCompare(y.date+'T'+y.time)}),work=0,br=0,workAt=null,breakAt=null;function ms(x){var d=new Date((x.date||'')+'T'+(x.time||'00:00')+':00');return isNaN(d)?null:d.getTime()}a.forEach(function(x){var t=ms(x);if(t===null)return;if(x.type==='clockIn'){workAt=t}else if(x.type==='breakStart'){if(workAt!==null){work+=Math.max(0,t-workAt);workAt=null}breakAt=t}else if(x.type==='breakEnd'){if(breakAt!==null){br+=Math.max(0,t-breakAt);breakAt=null}workAt=t}else if(x.type==='clockOut'){if(workAt!==null){work+=Math.max(0,t-workAt);workAt=null}if(breakAt!==null){br+=Math.max(0,t-breakAt);breakAt=null}}});var now=Date.now();if(workAt!==null)work+=Math.max(0,now-workAt);if(breakAt!==null)br+=Math.max(0,now-breakAt);return{work:Math.floor(work/60000),breaks:Math.floor(br/60000)}}
function hm(m){return Math.floor(m/60)+'時間 '+(m%60)+'分'}
function ensureStyle(){if(document.getElementById('attendanceStyle'))return;var st=document.createElement('style');st.id='attendanceStyle';st.textContent='.att-panel{border:1px solid #e5e7eb}.att-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:10px}.att-btn{min-height:54px;border:1px solid #dbe3ee;border-radius:15px;background:#fff;font-weight:950;color:#111827}.att-btn span{display:block;font-size:17px;margin-bottom:2px}.att-btn.in{background:#ecfdf5;color:#047857}.att-btn.out{background:#fff1f2;color:#be123c}.att-btn.break{background:#fff7ed;color:#c2410c}.att-btn.resume{background:#eff6ff;color:#1d4ed8}.att-btn:disabled{opacity:.35;filter:grayscale(.35);cursor:not-allowed}.att-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px}.att-stat{background:#f8fafc;border-radius:12px;padding:9px;text-align:center;font-size:11px;color:#64748b}.att-stat b{display:block;color:#111827;font-size:14px;margin-top:3px}.att-log{display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid #eef2f6}.att-icon{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:#f1f5f9}.att-edit{display:flex;gap:6px;flex-wrap:wrap}.att-edit input{border:1px solid #dbe3ee;border-radius:10px;padding:7px;font-size:12px}.att-del{border:1px solid #fecaca;background:#fff;color:#dc2626;border-radius:10px;padding:8px;font-weight:800}@media(max-width:430px){.att-actions{gap:5px}.att-btn{font-size:11px;min-height:60px}.att-log{grid-template-columns:36px 1fr}.att-edit{grid-column:2}.att-edit input{max-width:135px}}';document.head.appendChild(st)}
function panelHtml(){return '<div class="head"><div><h2>勤怠（ワンタップ）</h2><div class="help">現在時刻を自動記録します。修正は「勤怠」タブからできます。</div><div class="small att-sync">保存状態を確認中…</div></div><button type="button" id="attDetail" class="ghost">詳細</button></div><div class="att-actions"><button class="att-btn in" data-att="clockIn"><span>▶</span>出勤</button><button class="att-btn out" data-att="clockOut"><span>■</span>退勤</button><button class="att-btn break" data-att="breakStart"><span>☕</span>休憩</button><button class="att-btn resume" data-att="breakEnd"><span>▶</span>休憩終了</button></div><div class="att-stats"><div class="att-stat">現在の状態<b id="attStatus">未出勤</b></div><div class="att-stat">本日の稼働<b id="attWork">0時間 0分</b></div><div class="att-stat">休憩<b id="attBreak">0分</b></div></div>'}
function ensureHome(){var home=document.getElementById('view-home');if(!home)return null;var p=document.getElementById('attendanceHomePanel');if(!p){p=document.createElement('section');p.id='attendanceHomePanel';p.className='panel att-panel';p.innerHTML=panelHtml();var panels=home.querySelectorAll(':scope > .panel');if(panels.length>1)panels[1].insertAdjacentElement('afterend',p);else home.appendChild(p);p.querySelectorAll('[data-att]').forEach(function(b){b.onclick=function(){add(b.dataset.att)}});p.querySelector('#attDetail').onclick=function(){openView()}}return p}
function ensureView(){var main=document.getElementById('mainArea');if(!main)return null;var v=document.getElementById('view-attendance');if(!v){v=document.createElement('section');v.id='view-attendance';v.className='view';v.innerHTML='<section class="panel"><div class="head"><div><h2>勤怠ログ</h2><div class="help">出勤・退勤・休憩の記録を後から修正できます。</div><div class="small att-sync">保存状態を確認中…</div></div></div><div id="attendanceLogList"></div></section>';main.appendChild(v)}return v}
function openView(){ensureView();document.querySelectorAll('.view').forEach(function(x){x.classList.remove('active')});var v=document.getElementById('view-attendance');if(v)v.classList.add('active');document.querySelectorAll('.cb-nav-btn').forEach(function(x){x.classList.toggle('active',x.dataset.view==='attendance')});render()}
function ensureNav(){var grid=document.querySelector('.cb-custom-nav-grid');if(!grid||grid.querySelector('[data-view="attendance"]'))return;grid.style.gridTemplateColumns='repeat(7,1fr)';var b=document.createElement('button');b.type='button';b.className='cb-nav-btn';b.dataset.view='attendance';b.innerHTML='<span class="ico">▣</span>勤怠';b.onclick=openView;var analysis=grid.querySelector('[data-view="analysis"]');if(analysis)grid.insertBefore(b,analysis);else grid.appendChild(b)}
function editLog(id,key,val){var s=state();if(!s)return;var a=logs(s).slice(),x=a.find(function(z){return z.id===id});if(!x)return;x[key]=val;s.attendanceLogs=a;persist(s,'勤怠時刻を更新しました');render()}
function delLog(id){var s=state();if(!s)return;s.attendanceLogs=logs(s).filter(function(x){return x.id!==id});persist(s,'勤怠ログを削除しました');render()}
function render(){ensureStyle();var s=state();if(!s)return;var p=ensureHome();ensureView();ensureNav();var st=status(s),m=mins(s);if(p){p.querySelector('#attStatus').textContent=st.label;p.querySelector('#attWork').textContent=hm(m.work);p.querySelector('#attBreak').textContent=m.breaks+'分';p.querySelectorAll('[data-att]').forEach(function(b){b.disabled=!validNext(s,b.dataset.att)})}var list=document.getElementById('attendanceLogList');if(list){var a=logs(s).slice().sort(function(x,y){return (y.date+'T'+y.time).localeCompare(x.date+'T'+x.time)});list.innerHTML=a.length?a.map(function(x){var t=TYPES[x.type]||{label:x.type,ico:'•'};return '<div class="att-log" data-id="'+x.id+'"><div class="att-icon">'+t.ico+'</div><div><b>'+t.label+'</b><div class="small">'+x.date+' '+x.time+'</div></div><div class="att-edit"><input type="date" data-key="date" value="'+(x.date||'')+'"><input type="time" data-key="time" value="'+(x.time||'')+'"><button type="button" class="att-del">削除</button></div></div>'}).join(''):'<div class="notice">勤怠ログはまだありません。</div>';list.querySelectorAll('.att-log').forEach(function(row){row.querySelectorAll('input').forEach(function(i){i.onchange=function(){editLog(row.dataset.id,i.dataset.key,i.value)}});row.querySelector('.att-del').onclick=function(){delLog(row.dataset.id)}})}}
var q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(function(){q=false;render()})}
window.addEventListener('DOMContentLoaded',function(){render();setTimeout(render,500);setTimeout(render,1400);setTimeout(syncD1,1600)});
window.addEventListener('online',syncD1);
document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')syncD1()});
document.addEventListener('click',function(){setTimeout(schedule,0)},true);
})();